apiVersion: v1
kind: Pod
metadata:
  name: back-app
spec:
  containers:
  - name: back-app
    image: broosted1/app-bro:latest
    ports:
    - containerPort: 8080
    resources:
      limits:
        memory: "400Mi"
        cpu: "500m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-scaler
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Pod
    name: back-app
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: back-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080