apiVersion: v1
kind: Pod
metadata:
  name: frontend-ui
  namespace: default
  labels:
    app: frontend-ui
spec:
  containers:
  - name: frontend-ui
    image: broosted1/front-bro:latest
    ports:
    - containerPort: 3000
    resources:
      limits:
        memory: "400Mi"
        cpu: "500m"