---
- hosts: localhost
  tasks:
  - name: Gather information about any instance with a tag key host and value master
    amazon.aws.ec2_instance_info:
      filters:
        tag:host: master
        instance-state-name: [ "running" ]
    register: data_struct
  - name: print all returned values
    debug:
      msg: "{{ [0,1,2] | map('extract',data_struct.instances,'instance_id') | list }}"
    
    
    
    