---
- hosts: aws_ec2
  become: yes
  tasks:
    - name: get update
      shell: |
              sudo apt-get update
    - name: install prereq
      apt:
        name: 
          - curl
          - apt-transport-https
          - ca-certificates
      
    - name: get kube packages
      ansible.builtin.shell: |
        sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
      
    - name: run this shell command for certs
      shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    
    - name: get update
      shell: |
              sudo apt-get update

    - name: install kube tools
      apt:
        name:
          - kubectl
          - kubelet
          - kubeadm
    
    - name: get update
      shell: |
              sudo apt-get update
    - name: install docker
      apt:
        name: 
          - gnupg
          - lsb-release
    - name: install docker continued
      shell: |
              sudo curl -fsSLo /usr/share/keyrings/docker-archive-keyring.gpg https://download.docker.com/linux/ubuntu/gpg
              echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
              sudo apt-get update
              sudo apt-get install -y docker-ce