---
- hosts: aws_ec2
  become: yes
  tasks:
    - name: copy file
      ansible.builtin.copy:
        src: aws-k8s-cni.yaml
        dest: aws-k8s-cni.yaml
        mode: 'u+x'

#kubectl apply -f aws-k8s-cni.yaml