---
- hosts: localhost
  tasks:
    - name: Gather information about any instance with a tag key host and value master
      amazon.aws.ec2_instance_info:
        filters:
          tag:host: master
          instance-state-name: [ "running" ]
      register: data_struct
    - name: create and start and TCP forwarding ELB for Control Plane cluster
      amazon.aws.elb_classic_lb:
          name: "cp-load-balancer"
          state: present
          instance_ids: "{{ [0,1,2] | map('extract',data_struct.instances,'instance_id') | list }}"
          purge_instance_ids: true
          scheme: internal
          security_group_ids: 'sg-07a0e1fd9f638844e'
          subnets:
              - subnet-db8bbca2
          listeners:
              - protocol: tcp # options are http, https, ssl, tcp
                load_balancer_port: 6443
                instance_port: 6443
