---
- hosts: localhost
  tasks:
      - name: terminate instances for master
        amazon.aws.ec2_instance:
            state: absent
            filters:
              tag:host: master
      - name: terminate instances for slave
        amazon.aws.ec2_instance:
            state: absent
            filters:
              tag:host: slave
      - name: terminate instance for load balancer
        amazon.aws.elb_classic_lb:
            name: "cp-load-balancer"
            state: absent