apiVersion: v1
kind: Pod
metadata:
  name: db-mongo
  namespace: default
  labels:
    app: db-mongo
spec:
  containers:
  - name: db-mongo
    image: broosted1/mongo-bro:latest
    ports:
    - containerPort: 27017
    resources:
      limits:
        memory: "400Mi"
        cpu: "500m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: db-scaler
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: Pod
    name: db-mongo
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
spec:
  selector:
    app: db-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017